language: scala

scala:
   - 2.10.7
   - 2.11.12

jdk:
   - oraclejdk7
   - oraclejdk8

matrix:
  include:
    - scala: 2.12.4
      jdk: oraclejdk8
      env:
        - TRAVIS_NODE_VERSION="6"

branches:
  except:
    - /^wip-.*$/

env:
  - TRAVIS_NODE_VERSION="6"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - which node
# small tricks to enable faster builds

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.nvm

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

script:
  # Your normal script
  - sbt ++$TRAVIS_SCALA_VERSION squantsJVM/test:compile squantsJS/test:compile squantsJS/fastOptJS
  - if [[ $TRAVIS_SCALA_VERSION == "2.11.11" ]]; then sbt ++$TRAVIS_SCALA_VERSION squantsNative/compile; fi;
  - sbt ++$TRAVIS_SCALA_VERSION squantsJS/test squantsJVM/test
  - sbt ++$TRAVIS_SCALA_VERSION squantsJS/doc squantsJVM/doc tut

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e50c1534becaa7b20529
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
